// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  citacoes_group: dynamic(() => import("./CitacoesGroup")),
  perks_informacoes: dynamic(() => import("./PerksInformacoes")),
};
