// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Hero documents
 */
interface HeroDocumentData {
  /**
   * titulo field in *Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * HeroImage field in *Hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Hero document from Prismic
 *
 * - **API ID**: `hero`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HeroDocumentData>, "hero", Lang>;

type PerksDocumentDataSlicesSlice = PerksInformacoesSlice;

/**
 * Content for perks documents
 */
interface PerksDocumentData {
  /**
   * Slice Zone field in *perks*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PerksDocumentDataSlicesSlice>;
}

/**
 * perks document from Prismic
 *
 * - **API ID**: `perks`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PerksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PerksDocumentData>, "perks", Lang>;

type ReviewsDocumentDataSlicesSlice = CitacoesGroupSlice;

/**
 * Content for Reviews documents
 */
interface ReviewsDocumentData {
  /**
   * Slice Zone field in *Reviews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewsDocumentDataSlicesSlice>;
}

/**
 * Reviews document from Prismic
 *
 * - **API ID**: `reviews`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsDocumentData>,
    "reviews",
    Lang
  >;

export type AllDocumentTypes = HeroDocument | PerksDocument | ReviewsDocument;

/**
 * Item in *CitacoesGroup → Default → Primary → Citacoes*
 */
export interface CitacoesGroupSliceDefaultPrimaryCitacoesItem {
  /**
   * texto field in *CitacoesGroup → Default → Primary → Citacoes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: citacoes_group.default.primary.citacoes[].texto
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;

  /**
   * autor field in *CitacoesGroup → Default → Primary → Citacoes*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: citacoes_group.default.primary.citacoes[].autor
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  autor: prismic.TitleField;
}

/**
 * Primary content in *CitacoesGroup → Default → Primary*
 */
export interface CitacoesGroupSliceDefaultPrimary {
  /**
   * Citacoes field in *CitacoesGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: citacoes_group.default.primary.citacoes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  citacoes: prismic.GroupField<
    Simplify<CitacoesGroupSliceDefaultPrimaryCitacoesItem>
  >;
}

/**
 * Default variation for CitacoesGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CitacoesGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CitacoesGroupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CitacoesGroup*
 */
type CitacoesGroupSliceVariation = CitacoesGroupSliceDefault;

/**
 * CitacoesGroup Shared Slice
 *
 * - **API ID**: `citacoes_group`
 * - **Description**: CitacoesGroup
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CitacoesGroupSlice = prismic.SharedSlice<
  "citacoes_group",
  CitacoesGroupSliceVariation
>;

/**
 * Item in *PerksInformacoes → Default → Primary → group*
 */
export interface PerksInformacoesSliceDefaultPrimaryGroupItem {
  /**
   * image field in *PerksInformacoes → Default → Primary → group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: perks_informacoes.default.primary.group[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *PerksInformacoes → Default → Primary → group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perks_informacoes.default.primary.group[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PerksInformacoes → Default → Primary → group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perks_informacoes.default.primary.group[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *PerksInformacoes → Default → Primary*
 */
export interface PerksInformacoesSliceDefaultPrimary {
  /**
   * group field in *PerksInformacoes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: perks_informacoes.default.primary.group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group: prismic.GroupField<
    Simplify<PerksInformacoesSliceDefaultPrimaryGroupItem>
  >;
}

/**
 * Default variation for PerksInformacoes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerksInformacoesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PerksInformacoesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PerksInformacoes*
 */
type PerksInformacoesSliceVariation = PerksInformacoesSliceDefault;

/**
 * PerksInformacoes Shared Slice
 *
 * - **API ID**: `perks_informacoes`
 * - **Description**: PerksInformacoes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerksInformacoesSlice = prismic.SharedSlice<
  "perks_informacoes",
  PerksInformacoesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeroDocument,
      HeroDocumentData,
      PerksDocument,
      PerksDocumentData,
      PerksDocumentDataSlicesSlice,
      ReviewsDocument,
      ReviewsDocumentData,
      ReviewsDocumentDataSlicesSlice,
      AllDocumentTypes,
      CitacoesGroupSlice,
      CitacoesGroupSliceDefaultPrimaryCitacoesItem,
      CitacoesGroupSliceDefaultPrimary,
      CitacoesGroupSliceVariation,
      CitacoesGroupSliceDefault,
      PerksInformacoesSlice,
      PerksInformacoesSliceDefaultPrimaryGroupItem,
      PerksInformacoesSliceDefaultPrimary,
      PerksInformacoesSliceVariation,
      PerksInformacoesSliceDefault,
    };
  }
}
